### ISSUE TITLE
This looks like spam

### ISSUE THREAD

**Issue by autarch** [THEMA-MEDIA/CPAN-foolishness#1]
I'm not sure why this is on CPAN. It looks sort of like spam. At the very least it probably belongs in the Acme namespace.

**Comment by vanHoesel** [comment]
Dave, I'm talking with Ingy and Gugod... And they think that it is okay to go ahead with this top-level name space... And yes I do see your concerns, but please don't worry about it.

**Comment by autarch** [comment]
My concern is not so much with the namespace as that the module doesn't do anything. It just looks like an ad.

**Comment by vanHoesel** [comment]
Okay, I must admit Dave, it was done in a hurry, and things did not really work out the way I desired it to be...

I will update the next few days to make it do better...

**Comment by davorg** [comment]
Theo,

Probably best to just remove this until you have something useful to put there. Currently, you just seem to run the risk of annoying people. And I'm sure that's not your intention.

**Comment by karenetheridge** [comment]
> Currently, you just seem to run the risk of annoying people

Yes, it makes you look like a jackass.
